development:
  adapter: postgresql
  encoding: unicode
  database: pethub_development
  pool: 5
  username: pethub
  password:
  #port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: pethub_test
  pool: 5
  username: pethub
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: pethub_production
  pool: 5
  username: pethub
  password: